[package]
name = "gui-client"
version = "0.1.0"
authors = ["cowboy8625 <43012445+cowboy8625@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "0.10.9"
